---
- hosts: all
  become: yes
  vars:
    username: swada
    #  vars_prompt:
    #    username: "Enter username"
  tasks:
    - name: more complex items to add several users
      user:
        name: "{{item.name}}"
        state: present
      with_items:
                - { name: web }
                - {name: labo }
                - {name: creative }
    - name: add a new user
      user:
        name: swada
        #group: web
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel\s'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    - user: name=swada group=wheel
    - name: install git
      yum: name=git state=latest
    - name: install tmux
      yum: name=tmux state=latest
    - name: SSM Agent install
      yum: name=https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm state=present
    - name: SSM Agent enable
      shell: "sudo systemctl enable amazon-ssm-agent"
    - name: SSM Agent start
      shell: "sudo systemctl start amazon-ssm-agent"
    - name: mkdir DocumentRoot
      file: path=/data/www/ 
            state=directory 
            owner=swada 
            group=web 
            mode=0755

- hosts: web
  become: yes
  tasks:
          - group:
              name: web
          # apche install
          - name: install apache
            yum: name=httpd state=latest
          - name: start apache and enable
            systemd: name=httpd state=started enabled=yes
          # index.html copy
          - name: change owner
            file: dest=/var/www/html owner=ec2-user recurse=yes
          - name: copy index.html
            copy: src=./index.html dest=/var/www/html/index.html owner=ec2-user
          # mkdir DocumentRoot
          - name: DocumentRoot location config file directory
            file: path=/data/www/ state=directory owner=labo group=labo mode=0755
          # php install
          - name: install php7
            shell: "sudo amazon-linux-extras install php7.2 -y"
          - name: install php lib
            yum: name={{item}} state=latest
            with_items:
                    - php-devel
                    - php-mbstring
                    - php-mysql
            notify:
                    - restart apache
  # install 終了後 apache 再起動
  handlers:
          - name: restart apache
            systemd:
              name: httpd 
              state: restarted

- hosts: web
